name: Build Eclipse RPC Plugin

on:
  push:
    branches: [ main ] #Branch pra executar a compilação

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8' #Sempre 8, se não nem compila

    - name: Compile .java files
      run: |
        mkdir -p bin
        javac -d bin $(find ./src -name "*.java")

    - name: Package JAR
      run: |
        jar cf EclipseRPCPlugin.jar -C bin .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EclipseRPCPlugin
        path: EclipseRPCPlugin.jar